### ISSUE TITLE
Error: all manifest columns missing even though manifest is correct

### ISSUE THREAD

**Issue by avanlinden** [Sage-Bionetworks/dccmonitor#112]
Ran into a weird issue validating Stefania Forner's metadata from the UCI Primary Screen study. When she uploaded the manifest as a tsv, dccvalidator generated an error saying that all the columns in the manifest were missing. I downloaded the tsv from the validation project to inspect it, and all the columns were present and filled out. Not sure what's going on but figured I would open an issue to track this in case it happens again. 

<img width="867" alt="Screen Shot 2021-05-17 at 10 35 16 AM" src="https://user-images.githubusercontent.com/11965371/118532250-994dee80-b6fb-11eb-9d86-beae6cbde230.png">

**Comment by Aryllen** [comment]
@avanlinden, is [this](https://www.synapse.org/#!Synapse:syn25716101) the file? If so, this is called a .tsv, but is not tab-delimited. The file is still comma separated.

**Comment by avanlinden** [comment]
@Aryllen Yep! Thanks for catching that -- that explains it. For some reason getting an actual tsv from her has been really challenging (went through a couple versions of txt files before this).

**Comment by Aryllen** [comment]
Happy to help!
