### ISSUE TITLE
dccmonitor doean't checking missing columns in biospecimen

### ISSUE THREAD

**Issue by danlu1** [Sage-Bionetworks/dccmonitor#127]
Here attached the different messages generated by dccvalidator and dccmonitor for test data.
dccvalidator:
<img width="1119" alt="dccvalidator" src="https://user-images.githubusercontent.com/90745557/158678692-97aeb4a2-910a-41d2-b474-d78fedf5e602.png">
dccmonitor: 
<img width="1182" alt="dccmonitor" src="https://user-images.githubusercontent.com/90745557/158678741-da307478-5749-4239-8d9c-8c87ce67bd7f.png">

**Comment by danlu1** [comment]
[individual_human_pass.csv](https://github.com/Sage-Bionetworks/dccmonitor/files/8271272/individual_human_pass.csv)
[assay_ATACseq_pass.csv](https://github.com/Sage-Bionetworks/dccmonitor/files/8271273/assay_ATACseq_pass.csv)
[manifest_RNAseq_pass.txt](https://github.com/Sage-Bionetworks/dccmonitor/files/8271274/manifest_RNAseq_pass.txt)
[biospecimen_pass.csv](https://github.com/Sage-Bionetworks/dccmonitor/files/8271275/biospecimen_pass.csv)

**Comment by afwillia** [comment]
Thought I fixed that here https://github.com/Sage-Bionetworks/dccmonitor/issues/123#issuecomment-1018038654 but apparently not! I will investigate when I get a chance.

**Comment by danlu1** [comment]
I suggest to modify the line 113-122 to 
` if ("biospecimenType" %in% names(study_table)) {
    biospecimen_type <- unique(stats::na.omit(study_table[["biospecimenType"]]))
    # It's possible to get a column of NaN, NA, NULL; check length in case
    if (length(biospecimen_type) < 1){
      biospecimen_type <- NA
    } else {
      biospecimen_type[biospecimen_type %in% c("NaN","")] <- NA
      biospecimen_type <- unique(stats::na.omit(biospecimen_type))
    }
  }`
