### ISSUE TITLE
Incorporate additional metadata terms

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/dccmonitor#31]
Right now we get the synapse annotations here: https://github.com/Sage-Bionetworks/dccmonitor/blob/736a45c97de0fdd770caf1a4c798ee88610c9ff9/R/app-server.R#L39

In the AMP-AD version of the app, we also use some [additional definitions](https://github.com/Sage-Bionetworks/dccvalidator/blob/e9ae171c2166d5940576103f9d995e9ca17a87d7/R/app-server.R#L94-L98) that are listed in the config file. 

Can we add a configuration option for this in dccmonitor as well?

**Comment by Aryllen** [comment]
For sure. I can add that.
